/**
 * Export synthesis: package one generated plugin version as an installable
 * zip — byte-for-byte the release format `@snap-rail/plugin-kit/pack`
 * assembles for repo-built packages (a trimmed manifest, the host face,
 * and — when the version has one — the client face; never sources). The
 * function bodies are wrapped, not rebuilt: the host half rides an ESM
 * shim whose static imports map onto the runner's require whitelist (the
 * pool's resolve-hooks anchor those bare ids to the app root), and the
 * client half is already the clientBundle factory shape the renderer's
 * module loader registers.
 *
 * @module @snap-rail/forge/export
 */

import { zipSync } from 'fflate'
import type { VersionRecord } from './registry.ts'
import { HOST_REQUIRE_IDS, scanRequires } from './runner.ts'

/** The package name an exported plugin takes on the wire and in plugins.yml. */
export function exportPackageName(pluginId: string): string {
  return `@forge/${pluginId}`
}

/** What one export carries into {@link buildExportZip}. */
export interface ExportInput {
  /** The immutable version record (sources included). */
  version: VersionRecord
  /** The plugin's display title (rides the manifest description prefix). */
  title: string
  /** The plugin's description. */
  description: string
}

/**
 * Assemble the export's file set (the zip's logical content, before
 * compression). Mirrors `releaseFiles`' layout rules: manifest at the root,
 * faces in their directories, nothing else.
 *
 * @param input - the version to package.
 * @returns the files keyed by package-relative path.
 * @throws when the version has no host half (the manifest's `main` would
 * dangle — client-only versions are runtime-only and not exportable).
 */
export function buildExportFiles(input: ExportInput): Record<string, Uint8Array> {
  const { version, title, description } = input
  if (version.hostSrc === null) {
    throw new Error(`版本 ${version.versionId} 没有宿主半边，无法导出为可安装插件`)
  }
  const encoder = new TextEncoder()
  const pkgName = exportPackageName(version.pluginId)
  const manifest: Record<string, unknown> = {
    name: pkgName,
    version: `0.${version.seq}.0`,
    description: description === '' ? title : description,
    type: 'module',
    main: 'host/index.js',
    snapRail: version.clientSrc === null
      ? { kind: 'plugin' }
      : { kind: 'plugin', client: { entry: 'client/client.js' } },
  }
  const files: Record<string, Uint8Array> = {
    'package.json': encoder.encode(`${JSON.stringify(manifest, null, 2)}\n`),
    'host/index.js': encoder.encode(hostShim(version.hostSrc)),
  }
  if (version.clientSrc !== null) {
    files['client/client.js'] = encoder.encode(clientWrapper(version.clientSrc, pkgName))
  }
  return files
}

/** Compress the export's file set into the zip bytes an install consumes. */
export function buildExportZip(input: ExportInput): Uint8Array {
  return zipSync(buildExportFiles(input), { level: 9 })
}

/**
 * The host-face shim: an ESM module that reconstructs the runner's require
 * whitelist from static imports (resolve-hooks anchor these to the app
 * root), replays the stored function body over it, and default-exports the
 * plugin object. Only the ids the body actually requires become imports.
 */
function hostShim(src: string): string {
  const required = [...new Set(scanRequires(src))].filter(id => HOST_REQUIRE_IDS.includes(id))
  const imports = required.map((id, index) => `import * as m${index} from ${JSON.stringify(id)};`)
  const entries = required.map((id, index) => `  ${JSON.stringify(id)}: m${index},`)
  return `// Generated by @snap-rail/forge — the runtime plugin's host half, wrapped for the pool.
${imports.join('\n')}
const requireTable = {
${entries.join('\n')}
};
const require = (id) => {
  const module = requireTable[id];
  if (module === undefined) throw new Error('require("' + id + '") 不在宿主半边白名单内');
  return module;
};
const plugin = (new Function('require', ${JSON.stringify(`"use strict";\n${src}`)}))(require);
export default plugin;
`
}

/**
 * The client-face wrapper: the exact banner/footer shape plugin-kit's
 * `clientBundle` emits, carrying the stored factory body verbatim. The
 * pool's renderer executes this as a classic script; the id must equal the
 * plugins.yml row name the installer writes.
 */
function clientWrapper(src: string, pkgName: string): string {
  return `window.__ModuleLoader__.load({ id: ${JSON.stringify(pkgName)}, factory: function (require, module, exports) {
"use strict";
${src}
return module.exports && module.exports.__esModule === true && "default" in module.exports ? module.exports.default : module.exports; } });
`
}
